name: Gerar APK Nativo

on:
  push:
    branches:
      - main # Mude para 'master' se a sua branch principal tiver esse nome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Se seu projeto for mais antigo e usar Java 11, mude para '11'

      - name: Conceder permissao de execucao para o Gradlew
        run: chmod +x gradlew

      - name: Gerar o APK de Release
        run: ./gradlew assembleRelease

      - name: Upload do APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
